version: "2.1"
services:
    lumiere_ui:
        container_name: "lumiere_ui"
        build: 
            dockerfile: ./Dockerfile.dev
            context: ../ui
        working_dir: /app
        ports:
            - 3000:3000
        volumes:
            - ../ui:/app
        command: start
        stdin_open: true
        environment:
            - REACT_APP_API_ENDPOINT=http://localhost:8000/api
    lumiere_core:
        container_name: "lumiere_core"
        ports:
            - 8000:8000
        volumes:
            - btcd_certs:/certs
            - ..:/app
        build:
            dockerfile: ./dev
            context: .
        env_file:
            - ../.env
        depends_on: 
            - btcd
        links:
            - btcd
    btcd:
        container_name: "btcd"
        build:
            dockerfile: ./btcd
            context: .
        volumes:
            - btcd_data:/root/.btcd
            - btcd_certs:/certs
        ports:
            - 127.0.0.1:18334:18334
            - 18333:18333
        env_file:
            - ../.env

volumes:
    btcd_certs:
        external: true
    btcd_data:
        external: true